### ISSUE TITLE
Repo Eksik

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [huseyinkucuk82/RaceGameSample1#1]
Merhaba hocam reponuz eksik her hangi bir kod icermiyor git hakkinda ogrenmeniz 1 gun en fazla cok basit tesekkurler hocam

**Comment by huseyinkucuk82** [comment]
Nasıl öğreneceğiz? Nereden öğreneceğiz? Github .net’i desteklemiyor mu acaba?

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

________________________________
Gönderen: Abdulrahman Elheyb <notifications@github.com>
Gönderildi: Thursday, August 13, 2020 9:06:01 PM
Kime: huseyinkucuk82/RaceGameSample1 <RaceGameSample1@noreply.github.com>
Bilgi: Subscribed <subscribed@noreply.github.com>
Konu: [huseyinkucuk82/RaceGameSample1] Repo Eksik (#1)


Merhaba hocam reponuz eksik her hangi bir kod icermiyor git hakkinda ogrenmeniz 1 gun en fazla cok basit tesekkurler hocam

**Comment by Abdulrahmanelheyb** [comment]
.NET Destekliyor VIsual Studio'da var bildirim zili'nin yaninda projenin adi var tiklayinca git'ti olusturacak .

**Comment by huseyinkucuk82** [comment]
Tamam Elhib. Bir ara visual studio üzerinden de öğret bana şu işi.

**Comment by Abdulrahmanelheyb** [comment]
tamam hocam :)
